export const FETCH_PERSON_SUCCESS = 'FETCH_PERSON_SUCCESS'

export const FETCH_PERSONS_SUCCESS = 'FETCH_PERSONS_SUCCESS'

export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS'

export const SET_DEV_PREVIEW = 'SET_DEV_PREVIEW'
