<?php
  require_once "../includes/db.inc";
  require_once "../includes/cart_session.inc";
  require_once "../includes/location.inc";
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
    <title>TuneIn - <?php echo $title; ?></title>
    <link rel="stylesheet" href="../styles/tunein.css" type="text/css" />
    <script type="text/javascript" src="../scripts/ie_css.js"></script>
  </head>
</html>
