#!/usr/bin/env ruby

def window_present?
  `wmctrl -l | grep \\(superplan\\) | wc -l`.to_i > 0
end

def focus_window
  `wmctrl -a \\(superplan\\)`
end

def launch
  `(e --project /home/daniel/Dropbox/Superplan/superplan.sublime-project /home/daniel/Dropbox/Superplan/superplan.smd) &`
end

if window_present?
  focus_window
else
  launch
end

