module.exports = {
  DB_URI: process.env.DB_URI,
  AUTH0_NAMESPACE: process.env.AUTH0_NAMESPACE,
  AUTH0_TOKEN_URL: process.env.AUTH0_TOKEN_URL,
  AUTH0_CLIENT_ID: process.env.AUTH0_CLIENT_ID,
  AUTH0_CLIENT_SECRET: process.env.AUTH0_CLIENT_SECRET,
  AUTH0_AUDIENCE: process.env.AUTH0_AUDIENCE,
  AUTH0_DOMAIN: process.env.AUTH0_DOMAIN,
};
