#!/bin/bash

cat <<EOH >> /etc/default/elasticsearch
ES_HEAP_SIZE=128m
MAX_LOCKED_MEMORY=100000
EOH

cat <<EOH > /usr/share/elasticsearch/config/elasticsearch.yml
cluster.name: es-${ELASTICSEARCH_VERSION}
http.host: 0.0.0.0
EOH

exec /docker-entrypoint.sh elasticsearch
