FROM python:3.6.6-alpine3.6


RUN pip install --trusted-host pypi.python.org -r requirements.txt

RUN pip install jupyter

RUN useradd -ms /bin/bash jupyter

USER jupyter


WORKDIR /home/jupyter

ENTRYPOINT ['jupyter', "notebook", "--ip=*"]
