require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SharingsController do

  def mock_sharing(stubs={})
    @mock_sharing ||= mock_model(Sharing, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all sharings as @sharings" do
      Sharing.stub(:all) { [mock_sharing] }
      get :index
      assigns(:sharings).should eq([mock_sharing])
    end
  end
end
