// flow-typed signature: 64f548d3e149a43a0224407d9838bbdd
// flow-typed version: <<STUB>>/favicons-webpack-plugin_v^0.0.9/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'favicons-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'favicons-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'favicons-webpack-plugin/lib/cache' {
  declare module.exports: any;
}

declare module 'favicons-webpack-plugin/lib/compiler' {
  declare module.exports: any;
}

declare module 'favicons-webpack-plugin/lib/favicons' {
  declare module.exports: any;
}

// Filename aliases
declare module 'favicons-webpack-plugin/index' {
  declare module.exports: $Exports<'favicons-webpack-plugin'>;
}
declare module 'favicons-webpack-plugin/index.js' {
  declare module.exports: $Exports<'favicons-webpack-plugin'>;
}
declare module 'favicons-webpack-plugin/lib/cache.js' {
  declare module.exports: $Exports<'favicons-webpack-plugin/lib/cache'>;
}
declare module 'favicons-webpack-plugin/lib/compiler.js' {
  declare module.exports: $Exports<'favicons-webpack-plugin/lib/compiler'>;
}
declare module 'favicons-webpack-plugin/lib/favicons.js' {
  declare module.exports: $Exports<'favicons-webpack-plugin/lib/favicons'>;
}
