// flow-typed signature: e23469136c162fe02dae5339d0a7fa7d
// flow-typed version: <<STUB>>/gulp-notify_v^3.2.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-notify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-notify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-notify/examples/gulpfile' {
  declare module.exports: any;
}

declare module 'gulp-notify/examples/jshint' {
  declare module.exports: any;
}

declare module 'gulp-notify/lib/extra_api' {
  declare module.exports: any;
}

declare module 'gulp-notify/lib/notify' {
  declare module.exports: any;
}

declare module 'gulp-notify/lib/report' {
  declare module.exports: any;
}

declare module 'gulp-notify/lib/withReporter' {
  declare module.exports: any;
}

declare module 'gulp-notify/test/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-notify/examples/gulpfile.js' {
  declare module.exports: $Exports<'gulp-notify/examples/gulpfile'>;
}
declare module 'gulp-notify/examples/jshint.js' {
  declare module.exports: $Exports<'gulp-notify/examples/jshint'>;
}
declare module 'gulp-notify/index' {
  declare module.exports: $Exports<'gulp-notify'>;
}
declare module 'gulp-notify/index.js' {
  declare module.exports: $Exports<'gulp-notify'>;
}
declare module 'gulp-notify/lib/extra_api.js' {
  declare module.exports: $Exports<'gulp-notify/lib/extra_api'>;
}
declare module 'gulp-notify/lib/notify.js' {
  declare module.exports: $Exports<'gulp-notify/lib/notify'>;
}
declare module 'gulp-notify/lib/report.js' {
  declare module.exports: $Exports<'gulp-notify/lib/report'>;
}
declare module 'gulp-notify/lib/withReporter.js' {
  declare module.exports: $Exports<'gulp-notify/lib/withReporter'>;
}
declare module 'gulp-notify/test/main.js' {
  declare module.exports: $Exports<'gulp-notify/test/main'>;
}
