// flow-typed signature: c17e01e6890c5f3b83007435a82551d1
// flow-typed version: <<STUB>>/gulp-sizereport_vgit://github.com/jaysalvat/gulp-sizereport.git/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-sizereport'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-sizereport' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'gulp-sizereport/index' {
  declare module.exports: $Exports<'gulp-sizereport'>;
}
declare module 'gulp-sizereport/index.js' {
  declare module.exports: $Exports<'gulp-sizereport'>;
}
