// flow-typed signature: df02b653fef0323efee337ccc366f688
// flow-typed version: <<STUB>>/modernizr-loader_v^1.0.1/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'modernizr-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'modernizr-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'modernizr-loader/test/fixtures/index-json' {
  declare module.exports: any;
}

declare module 'modernizr-loader/test/fixtures/index' {
  declare module.exports: any;
}

declare module 'modernizr-loader/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'modernizr-loader/index' {
  declare module.exports: $Exports<'modernizr-loader'>;
}
declare module 'modernizr-loader/index.js' {
  declare module.exports: $Exports<'modernizr-loader'>;
}
declare module 'modernizr-loader/test/fixtures/index-json.js' {
  declare module.exports: $Exports<'modernizr-loader/test/fixtures/index-json'>;
}
declare module 'modernizr-loader/test/fixtures/index.js' {
  declare module.exports: $Exports<'modernizr-loader/test/fixtures/index'>;
}
declare module 'modernizr-loader/test/test.js' {
  declare module.exports: $Exports<'modernizr-loader/test/test'>;
}
