// flow-typed signature: 697031bddde7e656f95a585f6e012e8b
// flow-typed version: <<STUB>>/react-loadable-visibility_v^2.4.2/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-loadable-visibility'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-loadable-visibility' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-loadable-visibility/capacities' {
  declare module.exports: any;
}

declare module 'react-loadable-visibility/createLoadableVisibilityComponent' {
  declare module.exports: any;
}

declare module 'react-loadable-visibility/loadable-components' {
  declare module.exports: any;
}

declare module 'react-loadable-visibility/react-loadable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-loadable-visibility/capacities.js' {
  declare module.exports: $Exports<'react-loadable-visibility/capacities'>;
}
declare module 'react-loadable-visibility/createLoadableVisibilityComponent.js' {
  declare module.exports: $Exports<'react-loadable-visibility/createLoadableVisibilityComponent'>;
}
declare module 'react-loadable-visibility/index' {
  declare module.exports: $Exports<'react-loadable-visibility'>;
}
declare module 'react-loadable-visibility/index.js' {
  declare module.exports: $Exports<'react-loadable-visibility'>;
}
declare module 'react-loadable-visibility/loadable-components.js' {
  declare module.exports: $Exports<'react-loadable-visibility/loadable-components'>;
}
declare module 'react-loadable-visibility/react-loadable.js' {
  declare module.exports: $Exports<'react-loadable-visibility/react-loadable'>;
}
