// flow-typed signature: d9f26bbd8cc6e549e54f2cda583b0b1f
// flow-typed version: <<STUB>>/webpack-pwa-manifest_v^3.6.2/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-pwa-manifest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-pwa-manifest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-pwa-manifest/dist/errors/IconError' {
  declare module.exports: any;
}

declare module 'webpack-pwa-manifest/dist/errors/PresetError' {
  declare module.exports: any;
}

declare module 'webpack-pwa-manifest/dist/generators/legacy' {
  declare module.exports: any;
}

declare module 'webpack-pwa-manifest/dist/generators/tapable' {
  declare module.exports: any;
}

declare module 'webpack-pwa-manifest/dist/helpers/except' {
  declare module.exports: any;
}

declare module 'webpack-pwa-manifest/dist/helpers/fingerprint' {
  declare module.exports: any;
}

declare module 'webpack-pwa-manifest/dist/helpers/uri' {
  declare module.exports: any;
}

declare module 'webpack-pwa-manifest/dist/icons/index' {
  declare module.exports: any;
}

declare module 'webpack-pwa-manifest/dist/index' {
  declare module.exports: any;
}

declare module 'webpack-pwa-manifest/dist/injector/index' {
  declare module.exports: any;
}

declare module 'webpack-pwa-manifest/dist/validators/colors' {
  declare module.exports: any;
}

declare module 'webpack-pwa-manifest/dist/validators/presets' {
  declare module.exports: any;
}

declare module 'webpack-pwa-manifest/dist/validators/versioning' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-pwa-manifest/dist/errors/IconError.js' {
  declare module.exports: $Exports<'webpack-pwa-manifest/dist/errors/IconError'>;
}
declare module 'webpack-pwa-manifest/dist/errors/PresetError.js' {
  declare module.exports: $Exports<'webpack-pwa-manifest/dist/errors/PresetError'>;
}
declare module 'webpack-pwa-manifest/dist/generators/legacy.js' {
  declare module.exports: $Exports<'webpack-pwa-manifest/dist/generators/legacy'>;
}
declare module 'webpack-pwa-manifest/dist/generators/tapable.js' {
  declare module.exports: $Exports<'webpack-pwa-manifest/dist/generators/tapable'>;
}
declare module 'webpack-pwa-manifest/dist/helpers/except.js' {
  declare module.exports: $Exports<'webpack-pwa-manifest/dist/helpers/except'>;
}
declare module 'webpack-pwa-manifest/dist/helpers/fingerprint.js' {
  declare module.exports: $Exports<'webpack-pwa-manifest/dist/helpers/fingerprint'>;
}
declare module 'webpack-pwa-manifest/dist/helpers/uri.js' {
  declare module.exports: $Exports<'webpack-pwa-manifest/dist/helpers/uri'>;
}
declare module 'webpack-pwa-manifest/dist/icons/index.js' {
  declare module.exports: $Exports<'webpack-pwa-manifest/dist/icons/index'>;
}
declare module 'webpack-pwa-manifest/dist/index.js' {
  declare module.exports: $Exports<'webpack-pwa-manifest/dist/index'>;
}
declare module 'webpack-pwa-manifest/dist/injector/index.js' {
  declare module.exports: $Exports<'webpack-pwa-manifest/dist/injector/index'>;
}
declare module 'webpack-pwa-manifest/dist/validators/colors.js' {
  declare module.exports: $Exports<'webpack-pwa-manifest/dist/validators/colors'>;
}
declare module 'webpack-pwa-manifest/dist/validators/presets.js' {
  declare module.exports: $Exports<'webpack-pwa-manifest/dist/validators/presets'>;
}
declare module 'webpack-pwa-manifest/dist/validators/versioning.js' {
  declare module.exports: $Exports<'webpack-pwa-manifest/dist/validators/versioning'>;
}
declare module 'webpack-pwa-manifest/index' {
  declare module.exports: $Exports<'webpack-pwa-manifest'>;
}
declare module 'webpack-pwa-manifest/index.js' {
  declare module.exports: $Exports<'webpack-pwa-manifest'>;
}
