//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.209
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.209.
// 
namespace ExampleConfExtensionWebServiceClient.localhost {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://www.csharpwebservices.com/dummy ")]
    public class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        public SimpleAuthenticationSoapHeader SimpleAuthenticationSoapHeaderValue;
        
        /// <remarks/>
        public Service1() {
            this.Url = "http://localhost/Book/Chapter8/ExampleConfExtensionWebService/Service1.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SimpleAuthenticationSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.csharpwebservices.com/dummy /SayHello", RequestNamespace="http://www.csharpwebservices.com/dummy ", ResponseNamespace="http://www.csharpwebservices.com/dummy ", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SayHello(string who) {
            object[] results = this.Invoke("SayHello", new object[] {
                        who});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSayHello(string who, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SayHello", new object[] {
                        who}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSayHello(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SimpleAuthenticationSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.csharpwebservices.com/dummy /SayGoodbye", RequestNamespace="http://www.csharpwebservices.com/dummy ", ResponseNamespace="http://www.csharpwebservices.com/dummy ", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SayGoodbye(string who) {
            object[] results = this.Invoke("SayGoodbye", new object[] {
                        who});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSayGoodbye(string who, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SayGoodbye", new object[] {
                        who}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSayGoodbye(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csharpwebservices.com/dummy ")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.csharpwebservices.com/dummy ", IsNullable=false)]
    public class SimpleAuthenticationSoapHeader : SoapHeader {
        
        /// <remarks/>
        public string Password;
    }
}
