#!/bin/sh
#kill `cat pid`
#SECRET_KEY_BASE=$SECRET DATABASE_URL="ecto://postgres:postgres@127.0.01/database" PORT=4001 MIX_ENV=prod elixir --erl "-detached" -e "File.write! 'pid', :os.getpid" -S mix phx.server
SECRET_KEY_BASE=$SECRET DATABASE_URL="ecto://postgres:postgres@127.0.01/database" PORT=4001 MIX_ENV=prod _build/dev/rel/gbalbeat/bin/gbalbeat stop
SECRET_KEY_BASE=$SECRET DATABASE_URL="ecto://postgres:postgres@127.0.01/database" PORT=4001 MIX_ENV=prod _build/dev/rel/gbalbeat/bin/gbalbeat start
