version: "3.2"

volumes:
  src:

services:
  sut:
    build:
      context: .
      dockerfile: ./Dockerfile
      cache_from:
        - mhart/alpine-node:6
        - danielres/docker-react-node
    volumes:
      - .:/src
    # ports:
    # - 3000:3000
    # - 3001:3001
    links:
      - db
    depends_on:
      - db
    environment:
      NODE_ENV: test
      PGPASSWORD: mytribe
      PGUSER: mytribe
      PGDB: mytribe_test
    command: npm run _test:ci

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mytribe
      POSTGRES_USER: mytribe
      POSTGRES_DB: mytribe_test
