# Generated by Django 3.1.7 on 2021-03-30 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

<<<<<<< HEAD
    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='last_modified',
=======
    dependencies = [("notes", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="note",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="note",
            name="last_modified",
>>>>>>> 23fb4d348bb9c7b7b370cb2afcd785793e3816ea
            field=models.DateTimeField(auto_now=True),
        ),
    ]
