// Navigation
export const NAVIGATE_BACK = 'NAVIGATE_BACK'

// Auth
export const AUTH_CLEAR = 'AUTH_CLEAR'

// Register new user
export const REGISTER_STARTED = 'REGISTER_STARTED'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'

// Login user
export const LOGIN_STARTED = 'LOGIN_STARTED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

// Logout user
export const LOGOUT_STARTED = 'LOGOUT_STARTED'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

// Get authenticated user profile
export const GET_AUTHENTICATED_USER_STARTED = 'GET_AUTHENTICATED_USER_STARTED'
export const GET_AUTHENTICATED_USER_SUCCESS = 'GET_AUTHENTICATED_USER_SUCCESS'
export const GET_AUTHENTICATED_USER_FAILURE = 'GET_AUTHENTICATED_USER_FAILURE'

// User settings
export const USER_SETTINGS_CLEAR = 'USER_SETTINGS_CLEAR'

// Get authenticated user settings
export const GET_USER_SETTINGS_STARTED = 'GET_USER_SETTINGS_STARTED'
export const GET_USER_SETTINGS_SUCCESS = 'GET_USER_SETTINGS_SUCCESS'
export const GET_USER_SETTINGS_FAILURE = 'GET_USER_SETTINGS_FAILURE'

// Update authenticated user settings
export const UPDATE_USER_SETTINGS_STARTED = 'UPDATE_USER_SETTINGS_STARTED'
export const UPDATE_USER_SETTINGS_SUCCESS = 'UPDATE_USER_SETTINGS_SUCCESS'
export const UPDATE_USER_SETTINGS_FAILURE = 'UPDATE_USER_SETTINGS_FAILURE'

// Get all items
export const GET_ITEMS_RESET = 'GET_ITEMS_RESET'
export const GET_ITEMS_STARTED = 'GET_ITEMS_STARTED'
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS'
export const GET_ITEMS_FAILURE = 'GET_ITEMS_FAILURE'

// Get all items
export const GET_ITEM_RESET = 'GET_ITEM_RESET'
export const GET_ITEM_STARTED = 'GET_ITEM_STARTED'
export const GET_ITEM_SUCCESS = 'GET_ITEM_SUCCESS'
export const GET_ITEM_FAILURE = 'GET_ITEM_FAILURE'

// Get all users
export const GET_USERS_RESET = 'GET_USERS_RESET'
export const GET_USERS_STARTED = 'GET_USERS_STARTED'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE'

// Get user by username
export const GET_USER_RESET = 'GET_USER_RESET'
export const GET_USER_STARTED = 'GET_USER_STARTED'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILURE = 'GET_USER_FAILURE'

// Upload image
export const UPLOAD_IMAGE_STARTED = 'UPLOAD_IMAGE_STARTED'
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS'
export const UPLOAD_IMAGE_FAILURE = 'UPLOAD_IMAGE_FAILURE'

// Search items
export const SEARCH_ITEMS_RESET = 'SEARCH_ITEMS_RESET'
export const SEARCH_ITEMS_STARTED = 'SEARCH_ITEMS_STARTED'
export const SEARCH_ITEMS_SUCCESS = 'SEARCH_ITEMS_SUCCESS'
export const SEARCH_ITEMS_FAILURE = 'SEARCH_ITEMS_FAILURE'
