# Given two strings s and t which consist of only lowercase letters.
#
# String t is generated by random shuffling string s and then add one more letter at a random position.
#
# Find the letter that was added in t.
#
# Example:
#
# Input:
# s = "abcd"
# t = "abcde"
#
# Output:
# e
#
# Explanation:
# 'e' is the letter that was added.


class Solution:
    def findTheDifference(self, s, t):
        if not s:
            return t
        c = ord(s[0])

        for i in s[1:]:
            c = c ^ ord(i)
        for j in t:
            c = c ^ ord(j)

        return chr(c)
