#!/usr/bin/env fish

# Borrowed from gulp:

# Usage:
#
# To enable fish <tab> completion for app, add the following line to
# your ~/.config/fish/config.fish file:
#
# app --completion=fish | source

complete -c app -a "(app --tasks-simple)" -f
