(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},ca=ba(this),da=function(a,b){if(b)a:{var c=ca;a=a.split(".");for(var e=0;e<
a.length-1;e++){var f=a[e];if(!(f in c))break a;c=c[f]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&aa(c,a,{configurable:!0,writable:!0,value:b})}};da("Array.from",function(a){return a?a:function(b,c,e){c=null!=c?c:function(ka){return ka};var f=[],l="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof l){b=l.call(b);for(var m=0;!(l=b.next()).done;)f.push(c.call(e,l.value,m++))}else for(l=b.length,m=0;m<l;m++)f.push(c.call(e,b[m],m));return f}});
var d=this||self,ea=/^[\w+/_-]+[=]{0,2}$/,g=null,h=function(a){return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&ea.test(a)?a:""},k=function(a){return a};var fa=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,e="string"===typeof a?a.split(""):a,f=0;f<c;f++)if(f in e&&b.call(void 0,e[f],f,a))return!0;return!1};var n,p=function(){if(void 0===n){var a=null,b=d.trustedTypes;if(b&&b.createPolicy){try{a=b.createPolicy("goog#html",{createHTML:k,createScript:k,createScriptURL:k})}catch(c){d.console&&d.console.error(c.message)}n=a}else n=a}return n};var r=function(a,b){this.g=b===q?a:""};r.prototype.toString=function(){return this.g+""};var q={};var t;a:{var u=d.navigator;if(u){var v=u.userAgent;if(v){t=v;break a}}t=""};var x=function(a,b,c){this.g=c===w?a:""};x.prototype.toString=function(){return this.g.toString()};var w={};var y=function(a,b){if(!ha()){var c=Math.random();if(c<b)return c=ia(),a[Math.floor(c*a.length)]}return null},ia=function(){if(!d.crypto)return Math.random();try{var a=new Uint32Array(1);d.crypto.getRandomValues(a);return a[0]/65536/65536}catch(b){return Math.random()}},ha=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){return fa(["Google Web Preview","Mediapartners-Google","Google-Read-Aloud","Google-Adwords"],ja)||1E-4>Math.random()}),ja=function(a){return-1!=t.indexOf(a)};var la=function(a,b){b=void 0===b?!0:b;try{for(var c=null;c!=a;c=a,a=a.parent)switch(a.location.protocol){case "https:":return!0;case "file:":return b;case "http:":return!1}}catch(e){}return!0}(d,!1)?"https:":"http:";var z={u:1,l:4,m:5,j:7,o:9,s:10},A={i:"40004006",h:"40004007"};function ma(){return{1:.5,4:.02,5:.001,7:.5,9:.05,10:.2}}function na(){var a=B,b=typeof a;if(("object"!=b||null==a)&&"function"!=b)return!1;for(var c in z)if(b=a[z[c]],"number"!==typeof b||0>b||1<b)return!1;return!0};function oa(){var a=d.dcmads;if(null!=a.eids)return a.eids;var b=d.navigator;return b.connection&&b.connection.saveData?(a=y([A.i,A.h],a.expts[4]))?"4|"+a:"":""};try{d.dcmads=d.dcmads||{};d.dcmads.startTime=(new Date).getTime();var pa=d.dcmads,C=d.dcmads.version,D={loader:195};if(C)if(D.experiment=C.experiment,68==C.number||"p"==C.number)D.number=68;else if(68==C.number||"c"==C.number)D.number=68;if(!D.number){var E=y([68,68],0);D.experiment=!!E;D.number=E||68}pa.version=D;var qa=d.dcmads,F,B=d.dcmads.expts,G;G=void 0===G?ma:G;F=na()?B:G();qa.expts=F;d.dcmads.eids=oa();var ra="4|"+A.h,H=d.dcmads.version,I=H.number,J="";H.experiment&&68==I&&(J="?rxp=68x68");
var sa="impl_v"+I+".js"+J,K=d.document,L=K.currentScript||Array.from(K.getElementsByTagName("script")).pop(),M=(0==(L&&L.src||"").indexOf("http:")?"http:":"https:")+"//www.googletagservices.com/dcm/"+sa;if(d.dcmads.eids===ra){var N=d.document,O=p(),ta=O?O.createScriptURL(M):M,P=N.createElement("script"),Q=new r(ta,q);P.src=Q instanceof r&&Q.constructor===r?Q.g:"type_error:TrustedResourceUrl";var R;var S=P.ownerDocument&&P.ownerDocument.defaultView;S&&S!=d?R=h(S.document):(null===g&&(g=h(d.document)),
R=g);R&&P.setAttribute("nonce",R);var T=N.getElementsByTagName("script")[0];T&&T.parentNode&&T.parentNode.insertBefore(P,T)}else{var ua=d.document,U,va='<script src="'+M+'">\x3c/script>',wa=p(),xa=wa?wa.createHTML(va):va;U=new x(xa,null,w);ua.write(U instanceof x&&U.constructor===x?U.g:"type_error:SafeHtml")}}catch(a){if(.01>Math.random()){var V="";try{var W,X=a.toString();a.name&&-1==X.indexOf(a.name)&&(X+=": "+a.name);a.message&&-1==X.indexOf(a.message)&&(X+=": "+a.message);if(a.stack){var Y=a.stack,
Z=X;try{-1==Y.indexOf(Z)&&(Y=Z+"\n"+Y);for(var ya;Y!=ya;)ya=Y,Y=Y.replace(/((https?:\/..*\/)[^\/:]*:\d+(?:.|\n)*)\2/,"$1");X=Y.replace(/\n */g,"\n")}catch(b){X=Z}}W=X;W=W.substring(0,1024);V=encodeURIComponent(W)}catch(b){V="extr"}var za=d.dcmads.eids,Aa=document.createElement("img");Aa.src=la+"//pagead2.googlesyndication.com/pagead/gen_204?id=dcmads-err&ver=195&context=554"+((za?"&eids="+za:"")+"&msg="+V);(d.google_image_requests=d.google_image_requests||[]).push(Aa)}};}).call(this);
