(function(){var currentToken;var parentOrigin;var iframeOrigins;var RLT_KEY='jetpack:wpcomRLT';function getOriginFromUrl(url){var parser=document.createElement('a');parser.href=url;return parser.origin;}
function rltIframeInjector(event){if(!currentToken){return;}
rltInjectToken(currentToken,event.target.contentWindow,getOriginFromUrl(event.target.src));}
function rltMonitorIframes(){var iframes=document.querySelectorAll("iframe");for(var i=0;i<iframes.length;i++){var iframe=iframes[i];if(rltShouldAuthorizeIframe(iframe)){iframe.addEventListener('load',rltIframeInjector);}}
var observer=new MutationObserver(function(mutationsList,observer){for(var i=0;i<mutationsList.length;i++){var mutation=mutationsList[i];if(mutation.type==='childList'){for(var j=0;j<mutation.addedNodes.length;j++){var node=mutation.addedNodes[j];if(node instanceof HTMLElement&&node.nodeName==='IFRAME'&&rltShouldAuthorizeIframe(node)){node.addEventListener('load',rltIframeInjector);}}}}});observer.observe(document.body,{subtree:true,childList:true});}
function rltShouldAuthorizeIframe(iframe){if(!Array.isArray(iframeOrigins)){return;}
return iframeOrigins.indexOf(getOriginFromUrl(iframe.src))>=0;}
function rltInvalidateWindowToken(token,target,origin){pm({target:target,type:'rltMessage',data:{event:'invalidate',token:token,sourceOrigin:window.location.origin,},origin:origin});}
window.rltInvalidateToken=function(token,sourceOrigin){if(token===currentToken){currentToken=null;}
try{if(window.location===window.parent.location&&window.localStorage){if(window.localStorage.getItem(RLT_KEY)==token){window.localStorage.removeItem(RLT_KEY);}}}catch(e){console.info("localstorage access for invalidate denied - probably blocked third-party access",window.location.href);}
var iframes=document.querySelectorAll("iframe");for(var i=0;i<iframes.length;i++){var iframe=iframes[i];var iframeOrigin=getOriginFromUrl(iframe.src);if(iframeOrigin!==sourceOrigin&&rltShouldAuthorizeIframe(iframe)){rltInvalidateWindowToken(token,iframe.contentWindow,iframeOrigin);}}
if(parentOrigin&&parentOrigin!==sourceOrigin&&window.parent){rltInvalidateWindowToken(token,window.parent,parentOrigin);}}
window.rltInjectToken=function(token,target,origin){pm({target:target,type:'loginMessage',data:{event:'login',success:true,type:'rlt',token:token,sourceOrigin:window.location.origin,},origin:origin});};window.rltIsAuthenticated=function(){return!!currentToken;};window.rltGetToken=function(){return currentToken;};window.rltStoreToken=function(token){currentToken=token;try{if(window.location===window.parent.location&&window.localStorage){window.localStorage.setItem(RLT_KEY,token);}}catch(e){console.info("localstorage access denied - probably blocked third-party access",window.location.href);}}
window.rltInitialize=function(config){if(!config||typeof window.pm!=='function'){return;}
currentToken=config.token;iframeOrigins=config.iframeOrigins;parentOrigin=config.parentOrigin;try{if(!currentToken&&window.location===window.parent.location&&window.localStorage){currentToken=window.localStorage.getItem(RLT_KEY);}}catch(e){console.info("localstorage access denied - probably blocked third-party access",window.location.href);}
pm.bind('loginMessage',function(event){if('rlt'===event.type&&event.token&&event.token!==currentToken){rltStoreToken(event.token);var iframes=document.querySelectorAll("iframe");for(var i=0;i<iframes.length;i++){var iframe=iframes[i];if(rltShouldAuthorizeIframe(iframe)){rltInjectToken(currentToken,iframe.contentWindow,getOriginFromUrl(iframe.src));}}
if(parentOrigin&&parentOrigin!==event.sourceOrigin&&window.parent){rltInjectToken(currentToken,window.parent,parentOrigin);}}});pm.bind('rltMessage',function(event){if('invalidate'===event.event&&event.token&&event.token===currentToken){rltInvalidateToken(event.token);}});if(iframeOrigins){if(document.readyState!=='loading'){rltMonitorIframes();}else{window.addEventListener('DOMContentLoaded',rltMonitorIframes);}}};})();