#!/usr/bin/env python
"""
Solution to Project Euler Problem 45
http://projecteuler.net/

by Apalala <apalala@gmail.com>
(cc) Attribution-ShareAlike
http://creativecommons.org/licenses/by-sa/3.0/

Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

Triangle           Tn=n(n+1)/2            1, 3, 6, 10, 15, ...
Pentagonal         Pn=n(3n−1)/2           1, 5, 12, 22, 35, ...
Hexagonal          Hn=n(2n−1)             1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""
from series import exagonals, is_exagonal, is_pentagonal, is_triangle


def next_multiagonal(upfrom):
    for n in exagonals():
        if n > upfrom and is_pentagonal(n) and is_triangle(n):
            return n


def test():
    assert is_triangle(40755)
    assert is_pentagonal(40755)
    assert is_exagonal(40755)
    assert 40755 == next_multiagonal(40750)


def run():
    print(next_multiagonal(40755))


if __name__ == "__main__":
    test()
    run()
