export const types = {
  FETCH_OFFERS: "FETCH_OFFERS",
  FILTER_COMPANY: "companyName",
  FILTER_ADRESS: "customerAdress",

  SET_SEARCH_TEXT: "SET_SEARCH_TEXT",
  SET_FILTER_TYPE: "SET_FILTER_TEXT",
  SET_ACTIVE_OFFER: "SET_ACTIVE_OFFER",
  ADD_OFFER: "ADD_OVER",
};
