// flow-typed signature: 9757d8f561545d626c1f42f3bf0f22b5
// flow-typed version: <<STUB>>/db-migrate-pg_v^0.2.5/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'db-migrate-pg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "db-migrate-pg" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module "db-migrate-pg/index" {
  declare module.exports: $Exports<"db-migrate-pg">;
}
declare module "db-migrate-pg/index.js" {
  declare module.exports: $Exports<"db-migrate-pg">;
}
