// flow-typed signature: a2124c4d2e8ea6c47bb8f25ce635e275
// flow-typed version: <<STUB>>/db-migrate_v^0.10.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'db-migrate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "db-migrate" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "db-migrate/api" {
  declare module.exports: any;
}

declare module "db-migrate/connect" {
  declare module.exports: any;
}

declare module "db-migrate/lib/class" {
  declare module.exports: any;
}

declare module "db-migrate/lib/commands/create-migration" {
  declare module.exports: any;
}

declare module "db-migrate/lib/commands/db" {
  declare module.exports: any;
}

declare module "db-migrate/lib/commands/down" {
  declare module.exports: any;
}

declare module "db-migrate/lib/commands/fn/plugin" {
  declare module.exports: any;
}

declare module "db-migrate/lib/commands/helper/assert" {
  declare module.exports: any;
}

declare module "db-migrate/lib/commands/helper/load-config" {
  declare module.exports: any;
}

declare module "db-migrate/lib/commands/helper/migration-hook" {
  declare module.exports: any;
}

declare module "db-migrate/lib/commands/helper/register-events" {
  declare module.exports: any;
}

declare module "db-migrate/lib/commands/index" {
  declare module.exports: any;
}

declare module "db-migrate/lib/commands/on-complete" {
  declare module.exports: any;
}

declare module "db-migrate/lib/commands/run" {
  declare module.exports: any;
}

declare module "db-migrate/lib/commands/seed" {
  declare module.exports: any;
}

declare module "db-migrate/lib/commands/set-default-argv" {
  declare module.exports: any;
}

declare module "db-migrate/lib/commands/sync" {
  declare module.exports: any;
}

declare module "db-migrate/lib/commands/transition" {
  declare module.exports: any;
}

declare module "db-migrate/lib/commands/undo-seed" {
  declare module.exports: any;
}

declare module "db-migrate/lib/commands/up" {
  declare module.exports: any;
}

declare module "db-migrate/lib/config" {
  declare module.exports: any;
}

declare module "db-migrate/lib/driver/index" {
  declare module.exports: any;
}

declare module "db-migrate/lib/driver/shadow" {
  declare module.exports: any;
}

declare module "db-migrate/lib/interface/migratorInterface" {
  declare module.exports: any;
}

declare module "db-migrate/lib/interface/seederInterface" {
  declare module.exports: any;
}

declare module "db-migrate/lib/migration" {
  declare module.exports: any;
}

declare module "db-migrate/lib/migrator" {
  declare module.exports: any;
}

declare module "db-migrate/lib/relation" {
  declare module.exports: any;
}

declare module "db-migrate/lib/seed" {
  declare module.exports: any;
}

declare module "db-migrate/lib/seeder" {
  declare module.exports: any;
}

declare module "db-migrate/lib/skeleton" {
  declare module.exports: any;
}

declare module "db-migrate/lib/transitions/1" {
  declare module.exports: any;
}

declare module "db-migrate/lib/transitions/ask" {
  declare module.exports: any;
}

declare module "db-migrate/lib/transitions/transitioner" {
  declare module.exports: any;
}

declare module "db-migrate/lib/transitions/try-require" {
  declare module.exports: any;
}

declare module "db-migrate/lib/transitions/update-version" {
  declare module.exports: any;
}

// Filename aliases
declare module "db-migrate/api.js" {
  declare module.exports: $Exports<"db-migrate/api">;
}
declare module "db-migrate/connect.js" {
  declare module.exports: $Exports<"db-migrate/connect">;
}
declare module "db-migrate/index" {
  declare module.exports: $Exports<"db-migrate">;
}
declare module "db-migrate/index.js" {
  declare module.exports: $Exports<"db-migrate">;
}
declare module "db-migrate/lib/class.js" {
  declare module.exports: $Exports<"db-migrate/lib/class">;
}
declare module "db-migrate/lib/commands/create-migration.js" {
  declare module.exports: $Exports<"db-migrate/lib/commands/create-migration">;
}
declare module "db-migrate/lib/commands/db.js" {
  declare module.exports: $Exports<"db-migrate/lib/commands/db">;
}
declare module "db-migrate/lib/commands/down.js" {
  declare module.exports: $Exports<"db-migrate/lib/commands/down">;
}
declare module "db-migrate/lib/commands/fn/plugin.js" {
  declare module.exports: $Exports<"db-migrate/lib/commands/fn/plugin">;
}
declare module "db-migrate/lib/commands/helper/assert.js" {
  declare module.exports: $Exports<"db-migrate/lib/commands/helper/assert">;
}
declare module "db-migrate/lib/commands/helper/load-config.js" {
  declare module.exports: $Exports<"db-migrate/lib/commands/helper/load-config">;
}
declare module "db-migrate/lib/commands/helper/migration-hook.js" {
  declare module.exports: $Exports<"db-migrate/lib/commands/helper/migration-hook">;
}
declare module "db-migrate/lib/commands/helper/register-events.js" {
  declare module.exports: $Exports<"db-migrate/lib/commands/helper/register-events">;
}
declare module "db-migrate/lib/commands/index.js" {
  declare module.exports: $Exports<"db-migrate/lib/commands/index">;
}
declare module "db-migrate/lib/commands/on-complete.js" {
  declare module.exports: $Exports<"db-migrate/lib/commands/on-complete">;
}
declare module "db-migrate/lib/commands/run.js" {
  declare module.exports: $Exports<"db-migrate/lib/commands/run">;
}
declare module "db-migrate/lib/commands/seed.js" {
  declare module.exports: $Exports<"db-migrate/lib/commands/seed">;
}
declare module "db-migrate/lib/commands/set-default-argv.js" {
  declare module.exports: $Exports<"db-migrate/lib/commands/set-default-argv">;
}
declare module "db-migrate/lib/commands/sync.js" {
  declare module.exports: $Exports<"db-migrate/lib/commands/sync">;
}
declare module "db-migrate/lib/commands/transition.js" {
  declare module.exports: $Exports<"db-migrate/lib/commands/transition">;
}
declare module "db-migrate/lib/commands/undo-seed.js" {
  declare module.exports: $Exports<"db-migrate/lib/commands/undo-seed">;
}
declare module "db-migrate/lib/commands/up.js" {
  declare module.exports: $Exports<"db-migrate/lib/commands/up">;
}
declare module "db-migrate/lib/config.js" {
  declare module.exports: $Exports<"db-migrate/lib/config">;
}
declare module "db-migrate/lib/driver/index.js" {
  declare module.exports: $Exports<"db-migrate/lib/driver/index">;
}
declare module "db-migrate/lib/driver/shadow.js" {
  declare module.exports: $Exports<"db-migrate/lib/driver/shadow">;
}
declare module "db-migrate/lib/interface/migratorInterface.js" {
  declare module.exports: $Exports<"db-migrate/lib/interface/migratorInterface">;
}
declare module "db-migrate/lib/interface/seederInterface.js" {
  declare module.exports: $Exports<"db-migrate/lib/interface/seederInterface">;
}
declare module "db-migrate/lib/migration.js" {
  declare module.exports: $Exports<"db-migrate/lib/migration">;
}
declare module "db-migrate/lib/migrator.js" {
  declare module.exports: $Exports<"db-migrate/lib/migrator">;
}
declare module "db-migrate/lib/relation.js" {
  declare module.exports: $Exports<"db-migrate/lib/relation">;
}
declare module "db-migrate/lib/seed.js" {
  declare module.exports: $Exports<"db-migrate/lib/seed">;
}
declare module "db-migrate/lib/seeder.js" {
  declare module.exports: $Exports<"db-migrate/lib/seeder">;
}
declare module "db-migrate/lib/skeleton.js" {
  declare module.exports: $Exports<"db-migrate/lib/skeleton">;
}
declare module "db-migrate/lib/transitions/1.js" {
  declare module.exports: $Exports<"db-migrate/lib/transitions/1">;
}
declare module "db-migrate/lib/transitions/ask.js" {
  declare module.exports: $Exports<"db-migrate/lib/transitions/ask">;
}
declare module "db-migrate/lib/transitions/transitioner.js" {
  declare module.exports: $Exports<"db-migrate/lib/transitions/transitioner">;
}
declare module "db-migrate/lib/transitions/try-require.js" {
  declare module.exports: $Exports<"db-migrate/lib/transitions/try-require">;
}
declare module "db-migrate/lib/transitions/update-version.js" {
  declare module.exports: $Exports<"db-migrate/lib/transitions/update-version">;
}
