'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3705.209
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.209.
'
Namespace localhost
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="EmployeeServiceSoap", [Namespace]:="http://tempuri.org/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(System.Object()))>  _
    Public Class EmployeeService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/Employees/EmpService.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEmployee", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetEmployee(ByVal id As Integer) As EmployeeData
            Dim results() As Object = Me.Invoke("GetEmployee", New Object() {id})
            Return CType(results(0),EmployeeData)
        End Function
        
        '<remarks/>
        Public Function BeginGetEmployee(ByVal id As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetEmployee", New Object() {id}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetEmployee(ByVal asyncResult As System.IAsyncResult) As EmployeeData
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),EmployeeData)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ComputeEmployeePay", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ComputeEmployeePay(ByVal emp As EmployeeData) As Double
            Dim results() As Object = Me.Invoke("ComputeEmployeePay", New Object() {emp})
            Return CType(results(0),Double)
        End Function
        
        '<remarks/>
        Public Function BeginComputeEmployeePay(ByVal emp As EmployeeData, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ComputeEmployeePay", New Object() {emp}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndComputeEmployeePay(ByVal asyncResult As System.IAsyncResult) As Double
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Double)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllEmployees", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetAllEmployees() As Object()
            Dim results() As Object = Me.Invoke("GetAllEmployees", New Object(-1) {})
            Return CType(results(0),Object())
        End Function
        
        '<remarks/>
        Public Function BeginGetAllEmployees(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetAllEmployees", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetAllEmployees(ByVal asyncResult As System.IAsyncResult) As Object()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Object())
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(WageEmployee)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Boss))>  _
    Public MustInherit Class EmployeeData
        
        '<remarks/>
        Public Name As String
        
        '<remarks/>
        Public SSN As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Id As Integer
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public IdSpecified As Boolean
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Class WageEmployee
        Inherits EmployeeData
        
        '<remarks/>
        Public Wage As Double
        
        '<remarks/>
        Public Hours As Double
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Class Boss
        Inherits EmployeeData
        
        '<remarks/>
        Public Salary As Double
    End Class
End Namespace
