=pod

=head1 NAME

BOA::Logger - provides logging for the Big Ol' Application

=head1 SYNOPSIS

    my $logger = BOA::Logger->new("log_file");  # get new logger object
    $logger->level(10);                         # set log-level to 10
    $logger->write(1, "Hello log!");            # write a line at log-level 1

=head1 DESCRIPTION

BOA::Logger is an object-oriented class that provides access to a log file 
with an associated log-level.  Users of the module create a new BOA::Logger
object with the new() method.  The level() method is used to set the log-level
and the write() method is used to write lines to the log file.

=head1 AUTHOR

Sam Tregar <sam@tregar.com>

=head1 SEE ALSO

L<BOA>

=cut
