#!/bin/bash

filename='keys.txt'
filelines=`cat $filename`
echo Start
for line in $filelines ; do
    gpg --keyserver pgp.mit.edu --recv-keys $line;
    gpg --fingerprint $line;
    gpg --sign-key $line;
    gpg --keyserver pgp.mit.edu --send-keys $line;
done
