SELECT DEPARTMENT.NAME,
    COUNT(EMPLOYEE.DEPT_ID)
FROM
    DEPARTMENT
    LEFT JOIN EMPLOYEE 
    ON EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_ID
GROUP by
    DEPARTMENT.DEPT_ID
ORDER by
    COUNT(EMPLOYEE.DEPT_ID) DESC, 
    DEPARTMENT.NAME ASC