CREATE TABLE employees(
  ID         INTEGER  NOT NULL PRIMARY KEY ,
  First      VARCHAR(15) NOT NULL,
  Last       VARCHAR(15) NOT NULL,
  SSN        VARCHAR(15) NOT NULL,
  PROJECT_ID INTEGER  NOT NULL
);
