// flow-typed signature: c653ef0da18f6790bcb26c29e2417b53
// flow-typed version: <<STUB>>/@storybook/addon-viewport_v^3.4.2/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-viewport'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-viewport' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-viewport/dist/components/Panel' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/dist/components/RotateViewport' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/dist/components/SelectViewport' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/dist/components/styles' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/dist/components/viewportInfo' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/dist/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/src/components/Panel' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/src/components/RotateViewport' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/src/components/SelectViewport' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/src/components/styles' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/src/components/tests/Panel.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/src/components/tests/RotateViewport.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/src/components/tests/SelectViewport.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/src/components/tests/viewportInfo.spec' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/src/components/viewportInfo' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/src/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/src/tests/manager.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-viewport/dist/components/Panel.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/dist/components/Panel'>;
}
declare module '@storybook/addon-viewport/dist/components/RotateViewport.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/dist/components/RotateViewport'>;
}
declare module '@storybook/addon-viewport/dist/components/SelectViewport.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/dist/components/SelectViewport'>;
}
declare module '@storybook/addon-viewport/dist/components/styles.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/dist/components/styles'>;
}
declare module '@storybook/addon-viewport/dist/components/viewportInfo.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/dist/components/viewportInfo'>;
}
declare module '@storybook/addon-viewport/dist/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/dist/manager'>;
}
declare module '@storybook/addon-viewport/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/manager'>;
}
declare module '@storybook/addon-viewport/register.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/register'>;
}
declare module '@storybook/addon-viewport/src/components/Panel.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/src/components/Panel'>;
}
declare module '@storybook/addon-viewport/src/components/RotateViewport.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/src/components/RotateViewport'>;
}
declare module '@storybook/addon-viewport/src/components/SelectViewport.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/src/components/SelectViewport'>;
}
declare module '@storybook/addon-viewport/src/components/styles.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/src/components/styles'>;
}
declare module '@storybook/addon-viewport/src/components/tests/Panel.test.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/src/components/tests/Panel.test'>;
}
declare module '@storybook/addon-viewport/src/components/tests/RotateViewport.test.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/src/components/tests/RotateViewport.test'>;
}
declare module '@storybook/addon-viewport/src/components/tests/SelectViewport.test.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/src/components/tests/SelectViewport.test'>;
}
declare module '@storybook/addon-viewport/src/components/tests/viewportInfo.spec.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/src/components/tests/viewportInfo.spec'>;
}
declare module '@storybook/addon-viewport/src/components/viewportInfo.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/src/components/viewportInfo'>;
}
declare module '@storybook/addon-viewport/src/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/src/manager'>;
}
declare module '@storybook/addon-viewport/src/tests/manager.test.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/src/tests/manager.test'>;
}
