# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import mainapp.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InputFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zip_file",
                    models.FileField(
                        upload_to="zipinput/%Y/%m/%d",
                        validators=[mainapp.validators.validate_file_extension],
                    ),
                ),
            ],
        )
    ]
