# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("mainapp", "0002_auto_20160813_0245")]

    operations = [
        migrations.AddField(
            model_name="inputfile",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.Project",
            ),
        )
    ]
