# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import mainapp.validators


class Migration(migrations.Migration):

    dependencies = [("mainapp", "0003_inputfile_project")]

    operations = [
        migrations.AddField(
            model_name="image",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="thumb/%Y-%m-%d",
                validators=mainapp.validators.validate_image_extension,
            ),
        )
    ]
