# Generated by Django 3.1.7 on 2021-04-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

<<<<<<< HEAD
    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='img_url',
            field=models.CharField(default='http://https://i.stack.imgur.com/y9DpT.jpg', max_length=500),
        ),
=======
    dependencies = [("adventure", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="room",
            name="img_url",
            field=models.CharField(
                default="http://https://i.stack.imgur.com/y9DpT.jpg", max_length=500
            ),
        )
>>>>>>> 23fb4d348bb9c7b7b370cb2afcd785793e3816ea
    ]
