# Generated by cucumber-sinatra. (2013-08-10 21:48:02 +0200)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/kill_bill.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = KillBill
Capybara.save_and_open_page_path = 'tmp/capybara'

class KillBillWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  KillBillWorld.new
end
