export const FETCH_RENTALS = "FETCH_RENTALS";
export const RECIEVE_RENTALS = "RECIEVE_RENTALS";
export const RECIEVE_SELECTED_RENTAL = "RECIEVE_SELECTED_RENTAL";
export const REQUEST_SELECTED_RENTAL = "REQUEST_SELECTED_RENTAL";
export const FETCH_RENTALS_FAILURE = "FETCH_RENTALS_FAILURE";
export const REQUEST_RENTALS = "REQUEST_RENTALS";
export const REQUEST_RENTALS_SEARCH = "REQUEST_RENTALS_SEARCH";

export const CREATE_RENTAL_SUCCESS = "CREATE_RENTAL_SUCCESS";
export const CREATE_RENTAL_FAIL = "CREATE_RENTAL_FAIL";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const UPDATE_LOGIN_STATUS = "UPDATE_LOGIN_STATUS";

export const LOGOUT_USER = "LOGOUT_USER";

// BOOKING
export const REQUEST_BOOKING = "REQUEST_BOOKING";
export const BOOKING_SUCCESS = "BOOKING_SUCCESS";
export const BOOKING_FAILURE = "BOOKING_FAILURE";
export const CREATE_BOOKING = "CREATE_BOOKING";
export const INIT_USER = "INIT_USER";

export const REQUEST_BOOKINGS = "REQUEST_BOOKINGS";
export const RECIEVE_BOOKINGS = "RECIEVE_BOOKINGS";
export const RECIEVE_BOOKINGS_FAIL = "RECIEVE_BOOKINGS_FAIL";
