import { sanityClient, urlFor } from "lib/sanity";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "styles/Home.module.css";

const recipesQuery = `*[_type == "recipe"][0..3]|order(_createdAt desc){
                         _id, name, slug, mainImage
                      }`;

export async function getStaticProps() {
  const recipes = await sanityClient.fetch(recipesQuery);
  // console.log(recipes)
  return {
    props: {
      recipes,
    },
  };
}

export default function Home({ recipes }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>The Next Recipes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>The Recipe Blog</h1>

      <p>
        Hi there, This is a demo recipe app build with Nextjs and Sanity Cms.
      </p>
      {recipes?.length == 0 && <h2>Nothing is here!</h2>}

      <ul>
        {recipes?.length > 0 &&
          recipes.map((recipe) => (
            <li key={recipe._id}>
              <Link href={`/recipes/${recipe.slug.current}`}>
                <a>
                  <Image
                    src={urlFor(recipe.mainImage).url()}
                    width={300}
                    height={200}
                    objectFit={"cover"}
                    loading="lazy"
                    alt={recipe.name}
                  />

                  <span>{recipe.name}</span>
                </a>
              </Link>
            </li>
          ))}
      </ul>

      {recipes?.length > 0 && (
        <Link href="/recipes">
          <a className="btn">View All</a>
        </Link>
      )}
      <style jsx>{`
        p {
          margin-bottom: 1rem;
          font-size: 1.3rem;
        }
        a {
          color: inherit;
          text-decoration: none;
          display: flex;
          flex-direction: column;
        }
        .btn {
          font-weight: 600;
          padding: 0.5rem 1.5rem;
          background: white;
          color: #4b4b4b;
          border: 1px solid #b0b0b0;
          margin-top: 3rem;
        }

        span {
          font-size: 1.5rem;
          font-weight: 700;
          text-transform: capitalize;
          margin-top: 1.2rem;
          color: #747474;
        }
        ul {
          padding: 0;
          display: flex;
        }
        li {
          list-style: none;
          padding: 1rem;
          border: 1px solid #c9c9c9;
          margin-right: 0.5rem;
          background: white;
        }
      `}</style>
    </div>
  );
}
